version: '3.5'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/django
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  jenkins:
    container_name: jenkins
    build: 
      dockerfile: ./jenkins/Dockerfile
      context: .
    environment: 
      ENVSUBST_VARS: FQDN
      FQDN: localhost
    ports:
      - "8080:8080"
    volumes: 
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/django/
    expose:
      - "8000"
    depends_on:
      - db
  db:
    container_name: postresql
    image: postgres:latest
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
volumes: 
  jenkins_data: